OPENAI_API_KEY = "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"
OMNI_API_KEY = "bdudu4@dkndf45d"
[database]
keyvalue ="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"
