OPENAI_API_KEY = "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"
OMNI_API_KEY = "bdudu4@dkndf45d"
[database]
driver = "ODBC Driver 17 for SQL Server" # Or your specific driver name
server = "bizlyzer.database.windows.net,1433"
database = "BizlyzerBeta"
username = "BizlyzerDBA"
password = "B1zlyz3rDBA"
keyvalue ="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"
