OPENAI_API_KEY = "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"
OMNI_API_KEY = "bdudu4@dkndf45d"
[database]
keyvalue ="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"
