OPENAI_API_KEY = "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"
OMNI_API_KEY = "bdudu4@dkndf45d"
[database]
driver = "ODBC Driver 17 for SQL Server" # Or your specific driver name
server = "severname"
database = "databsename"
username = "username"
password = "password"
keyvalue ="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"