OPENAI_API_KEY = "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"
OMNI_API_KEY = "bdudu4@dkndf45d"
[database]
keyvalue ="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"
